# Generated by Django 3.2.9 on 2021-11-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_moviecomment_rank'),
        ('accounts', '0002_auto_20211119_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hate_genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='hate_genres', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_genres', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movies.Movie'),
        ),
    ]
