# Generated by Django 3.2.9 on 2021-11-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_moviecomment_rank'),
        ('accounts', '0003_auto_20211123_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_movies', to='movies.Movie'),
        ),
    ]
