# Generated by Django 3.2.9 on 2021-11-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='rank',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5),
        ),
    ]
